// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package main.java.softdesign;

/************************************************************/
/**
 * 
 */
public enum Direction {
	/**
	 * 
	 */
	NORTH,
	/**
	 * 
	 */
	NORTH_EAST,
	/**
	 * 
	 */
	EAST,
	/**
	 * 
	 */
	SOUTH_EAST,
	/**
	 * 
	 */
	SOUTH,
	/**
	 * 
	 */
	SOUTH_WEST,
	/**
	 * 
	 */
	WEST,
	/**
	 * 
	 */
	NORTH_WEST;
};
