// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package main.java.softdesign;

public interface Observer {
	/*
	 * Elements: Object of the type Subject. Observer is attached to the Subject to listen to its notifications
	 * and synchronize its state according to changes in the Subject;
	 * Domain: Task object of the type Subjects acts as a publisher of notifications for observers
	 */

	public void update();
	/* PRE  - observer has been attached to receive notifications from the Subject.
	   POST - observer's state has been synchronized according to the type of the change made in Subject.
	*/
};
