// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package main.java.softdesign;

/************************************************************/
/*Class Position represents the coordinate system of the environment*/
public class Position {
	/*position on the horizontal axes in the environment */
	private double x;
	
	/*position on the vertical axes in the environment*/
	private double y;

	/*Constructor for Position class */
	public Position(double x, double y) {
		this.x = x;
		this.y = y;
	}
	
	/*retrieving X coordinate*/
	public double getX() {
		return x;
	}

	/*retrieving Y coordinate*/
	public double getY() {
		return y;
	}
};
