// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package main.java.softdesign;

/************************************************************/
/**
 * 
 */
public enum RobotStatus {
	/**
	 * 
	 */
	CAMERAFAULT,
	/**
	 * 
	 */
	WHEELFAULT,
	/**
	 * 
	 */
	MOTORFAULT,
	/**
	 * 
	 */
	SENSORFAULT,
	/**
	 * 
	 */
	UNKNOWNFAULT,
	/**
	 * 
	 */
	NOERROR;
};
