// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package main.java.softdesign;
/************************************************************/
/**
 * 
 */
public enum TaskStatus {
	/**
	 * 
	 */
	START,
	/**
	 * 
	 */
	FAILED,
	/**
	 * 
	 */
	STOPPED,
	/**
	 * 
	 */
	COMPLETED;
};
